"""Describe the BTC/USDT order book dataset: sanity checks plus lobimb.data.describe.

Outputs:
    results/data_summary.json       machine-readable statistics + sanity report
    docs/report/data_summary.tex    LaTeX table fragment (Italian, no preamble;
                                    needs booktabs and float), \\label{tab:data-summary}

Usage:
    python scripts/describe_data.py [--json results/data_summary.json]
                                    [--tex docs/report/data_summary.tex]
                                    [--cache data/cache] [--source NAME]

For another dataset (e.g. the synthetic sample) pass --cache, --source and
output paths outside docs/ so the report table is not overwritten.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path

import pandas as pd

from lobimb import data
from lobimb.config import CACHE_DIR, PROJECT_ROOT, RAW_CSV, RESULTS_DIR, BacktestConfig


def _num(x: float, decimals: int = 0) -> str:
    """Italian number format for LaTeX: thin-space thousands, decimal comma."""
    s = f"{x:,.{decimals}f}"
    return s.replace(",", "\\,").replace(".", "{,}")


def _pct(share: float, decimals: int = 1) -> str:
    return _num(100 * share, decimals) + "\\%"


def _date(iso: str) -> str:
    return pd.Timestamp(iso).strftime("%d/%m/%Y %H:%M:%S")


def to_latex(d: dict, sanity: dict, csv_name: str) -> str:
    """LaTeX table fragment with Italian labels (needs booktabs and float)."""
    s, sp, bv, dv, o, sp_ = (d["sampling"], d["spread"], d["best_volume"],
                             d["depth10_volume"], d["obi"], d["split"])
    clean = "nessun problema" if not (sanity["non_monotonic_ts"] or sanity["crossed"]
                                      or sanity["non_positive_px"] or sanity["negative_vol"]
                                      or sanity["nan_rows"]) else "problemi rilevati"
    rows = [
        ("Periodo (UTC)", f"{_date(d['period']['start_utc'])} -- {_date(d['period']['end_utc'])}"),
        ("Durata", f"{_num(d['period']['duration_hours'], 1)} ore "
                   f"({_num(d['period']['duration_hours'] / 24, 1)} giorni)"),
        ("Snapshot", _num(d["n_snapshots"])),
        None,
        ("Intervallo tra snapshot: mediana / p99", f"{_num(s['median_dt_ms'])} / {_num(s['p99_dt_ms'])} ms"),
        ("Interruzioni (gap) $>$ 500 ms / $>$ 2 s", f"{_num(s['gaps_gt_500ms'])} / {_num(s['gaps_gt_2s'])}"),
        ("Gap massimo", f"{_num(s['max_dt_ms'] / 1000, 1)} s"),
        None,
        ("Prezzo medio (mid): min / max", f"{_num(d['price']['mid_min'], 2)} / {_num(d['price']['mid_max'], 2)} USDT"),
        ("Spread: mediana / media", f"{_num(sp['median'], 2)} / {_num(sp['mean'], 3)} USDT"),
        ("Spread: p99 / p99,9 / max", f"{_num(sp['p99'], 2)} / {_num(sp['p99_9'], 2)} / {_num(sp['max'], 1)} USDT"),
        ("Quota di spread pari a 1 tick (0,1 USDT)", _pct(sp["share_one_tick"])),
        None,
        ("Volume al best bid: mediana / media", f"{_num(bv['bid']['median'], 2)} / {_num(bv['bid']['mean'], 2)} BTC"),
        ("Volume al best ask: mediana / media", f"{_num(bv['ask']['median'], 2)} / {_num(bv['ask']['mean'], 2)} BTC"),
        ("Volume al best level $<$ 0,01 BTC (bid / ask)",
         f"{_pct(bv['bid']['share_lt_0_01'], 2)} / {_pct(bv['ask']['share_lt_0_01'], 2)}"),
        ("Volume al best level $<$ 1 BTC (bid / ask)",
         f"{_pct(bv['bid']['share_lt_1'])} / {_pct(bv['ask']['share_lt_1'])}"),
        ("Volume totale 10 livelli, bid: mediana / media", f"{_num(dv['bid']['median'], 1)} / {_num(dv['bid']['mean'], 1)} BTC"),
        ("Volume totale 10 livelli, ask: mediana / media", f"{_num(dv['ask']['median'], 1)} / {_num(dv['ask']['mean'], 1)} BTC"),
        None,
        ("OBI livello 1: media di $|\\mathrm{OBI}|$", _num(o["mean_abs"], 3)),
        ("Quota con $|\\mathrm{OBI}| > 0{,}6$ / $|\\mathrm{OBI}| = 1$",
         f"{_pct(o['share_abs_gt_0_6'])} / {_pct(o['share_abs_eq_1'])}"),
        None,
        (f"In-sample ({_num(100 * sp_['fraction'])}\\%)",
         f"{_num(sp_['in_sample_rows'])} snapshot, fino al {_date(sp_['in_sample_end_utc'])}"),
        (f"Out-of-sample ({_num(100 * (1 - sp_['fraction']))}\\%)",
         f"{_num(sp_['out_of_sample_rows'])} snapshot, dal {_date(sp_['out_of_sample_start_utc'])}"),
        ("Controlli di coerenza", f"{clean} (book incrociati: {_num(sanity['crossed'])}, "
                                  f"NaN: {_num(sanity['nan_rows'])}, timestamp non crescenti: "
                                  f"{_num(sanity['non_monotonic_ts'])})"),
    ]
    body = "\n".join("\\midrule" if r is None else f"{r[0]} & {r[1]} \\\\" for r in rows)
    name = csv_name.replace("_", "\\_")
    return f"""% Generated by scripts/describe_data.py from results/data_summary.json.
% Do not edit by hand: re-run the script after changing the dataset.
\\begin{{table}}[H]
\\centering
\\caption{{Statistiche descrittive del dataset BTC/USDT (\\texttt{{{name}}}): snapshot
del book a 10 livelli, campionati ogni 250 ms nominali.}}
\\label{{tab:data-summary}}
\\small
\\begin{{tabular}}{{p{{0.43\\linewidth}}p{{0.47\\linewidth}}}}
\\toprule
Grandezza & Valore \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--json", type=Path, default=RESULTS_DIR / "data_summary.json")
    parser.add_argument("--tex", type=Path, default=PROJECT_ROOT / "docs" / "report" / "data_summary.tex")
    parser.add_argument("--cache", type=Path, default=CACHE_DIR,
                        help="directory with the ts.npy/levels.npy cache")
    parser.add_argument("--source", default=RAW_CSV.name,
                        help="dataset name recorded in the outputs (default: %(default)s)")
    args = parser.parse_args()

    book = data.load(args.cache)
    sanity = asdict(data.sanity_check(book))
    summary = data.describe(book, in_sample_fraction=BacktestConfig().in_sample_fraction)
    out = {"source_csv": args.source, **summary, "sanity": sanity}

    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    args.tex.parent.mkdir(parents=True, exist_ok=True)
    args.tex.write_text(to_latex(summary, sanity, args.source), encoding="utf-8")

    print(json.dumps(out, indent=2))
    print(f"\nwritten {args.json} and {args.tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
